name: Notify libraries

on: push

jobs:
  generatePostman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: addnab/docker-run-action@v3
        with:
          image: gcatanese/openapi-generator-postman-v2
          options: -v ${{ github.workspace }}:/usr/src/app
          run: |
            sed -i.bak "1s/.*/openapi: 3.0.3/" yaml/CheckoutService-v69.yaml      
            rm yaml/CheckoutService-v69.yaml.bak      
            /script.sh generate -i yaml/CheckoutService-v69.yaml -o postman/CheckoutService-v69.postman
#      - uses: stefanzweifel/git-auto-commit-action@v4