name: Notify libraries

on: push

jobs:
  generatePostman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: addnab/docker-run-action@v3
        with:
          image: gcatanese/openapi-generator-postman-v2
          options: --platform linux/amd64
          run: |
            generate -i json/CheckoutService-v69.json -o CheckoutService-v69.postman