name: Notify libraries

on: push

jobs:
  generatePostman:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/checkout@v3
        with:
          repository: 'gcatanese/openapi-generator-postman-v2'
          path: 'generator'
      - name: Setup java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Run Java Generator
        run: java -cp target/openapi-generator-postman-v2.jar:/openapi-generator/modules/openapi-generator-cli/target/openapi-generator-cli.jar \
          org.openapitools.codegen.OpenAPIGenerator generate -g com.tweesky.cloudtools.codegen.PostmanV2Generator \
          -i json/CheckoutService-v69.json -o CheckoutService-v69.postman
      - uses: stefanzweifel/git-auto-commit-action@v4
#      - uses: addnab/docker-run-action@v3
#        with:
#          image: gcatanese/openapi-generator-postman-v2
#          options: --platform linux/amd64
#          run: |
#            generate -i json/CheckoutService-v69.json -o CheckoutService-v69.postman